### ISSUE TITLE
Any use case, to use this over require?

### ISSUE THREAD

**Issue by zikaari** [sindresorhus/req-from#4]
Just curious, maybe I should know something that's better than what I use right now, require?

**Comment by sindresorhus** [comment]
From the readme:

> Import a module like with require() **but from a given path**

Instead of importing relative to the current file, you can import relative to any file. So you can for example import a module relative to the user's current directory.

Example: https://github.com/sindresorhus/atom-esformatter/blob/b3c939215993f3c53ec66377ed6b631c025a97b2/index.js#L18
